name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          working_directory: 20200212
          root_file: 20200212_MONARC-training.tex

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          working_directory: 20200722
          root_file: 20200722_MONARC-training.tex

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          working_directory: 20201203
          root_file: 20201203_MONARC-training.tex

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          working_directory: 20210929
          root_file: 20210929_MONARC-training.tex

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          working_directory: 20220419
          root_file: 20220419_MONARC-training.tex

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          working_directory: 20221019
          root_file: 20221019_MONARC-training.tex

      - run: mkdir -p artifact
      - run: mv 20200212/20200212_MONARC-training.pdf artifact/

      - run: mkdir -p artifact
      - run: mv 20200722/20200722_MONARC-training.pdf artifact/

      - run: mkdir -p artifact
      - run: mv 20201203/20201203_MONARC-training.pdf artifact/

      - run: mkdir -p artifact
      - run: mv 20210929/20210929_MONARC-training.pdf artifact/

      - run: mkdir -p artifact
      - run: mv 20220419/20220419_MONARC-training.pdf artifact/

      - run: mkdir -p artifact
      - run: mv 20221019/20221019_MONARC-training.pdf artifact/


      - uses: actions/upload-artifact@v1
        with:
          name: MONARC-trainings.pdf
          path: artifact
