name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          working_directory: 20201203
          root_file: 20201203_MONARC-training.tex
          
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          working_directory: 20201203
          root_file: 20201203_MONARC-training.tex

      - run: mkdir -p artifact
      - run: mv 20201203/20201203_MONARC-training.pdf artifact/
      
      - run: mkdir -p artifact
      - run: mv 20201203/20201203_MONARC-training.pdf artifact/

      - uses: actions/upload-artifact@v1
        with:
          name: MONARC-trainings.pdf
          path: artifact
