name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          working_directory: presentation
          root_file: MONARC-training.tex

      - run: mkdir -p artifact
      - run: mv presentation/MONARC-training.pdf artifact/

      - uses: actions/upload-artifact@v1
        with:
          name: MONARC-training.pdf
          path: artifact
